const countries = [
    "Afghanistan",
    "Afrique du Sud",
    "Albanie",
    "Algérie",
    "Allemagne",
    "Andorre",
    "Angola",
    "Antigua-et-Barbuda",
    "Arabie Saoudite",
    "Argentine",
    "Arménie",
    "Australie",
    "Autriche",
    "Azerbaïdjan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbade",
    "Belgique",
    "Bélize",
    "Bénin",
    "Bhoutan",
    "Bolivie",
    "Bosnie-Herzégovine",
    "Botswana",
    "Brésil",
    "Brunéi",
    "Bulgarie",
    "Burkina Faso",
    "Burundi",
    "Cap-Vert",
    "Cambodge",
    "Cameroun",
    "Canada",
    "Centrafrique",
    "Chili",
    "Chine",
    "Chypre",
    "Colombie",
    "Comores",
    "Congo",
    "Congo, République Démocratique du",
    "Costa Rica",
    "Croatie",
    "Cuba",
    "Danemark",
    "Djibouti",
    "Dominique",
    "Égypte",
    "El Salvador",
    "Équateur",
    "Érythrée",
    "Espagne",
    "Estonie",
    "Eswatini",
    "États-Unis",
    "Fidji",
    "Finlande",
    "France",
    "Gabon",
    "Gambie",
    "Géorgie",
    "Ghana",
    "Grèce",
    "Grenade",
    "Guatemala",
    "Guinée",
    "Guinée-Bissau",
    "Guinée équatoriale",
    "Guyana",
    "Haïti",
    "Honduras",
    "Hongrie",
    "Inde",
    "Indonésie",
    "Irak",
    "Iran",
    "Irlande",
    "Islande",
    "Italie",
    "Jamaïque",
    "Japon",
    "Jordanie",
    "Kazakhstan",
    "Kenya",
    "Kirghizistan",
    "Kuwait",
    "Laos",
    "Lesotho",
    "Lettonie",
    "Lituanie",
    "Luxembourg",
    "Malaisie",
    "Malawi",
    "Maldives",
    "Mali",
    "Malte",
    "Maroc",
    "Marshall Islands",
    "Maurice",
    "Mauritanie",
    "Mexique",
    "Moldavie",
    "Monaco",
    "Mongolie",
    "Monténégro",
    "Myanmar",
    "Namibie",
    "Nauru",
    "Népal",
    "Nicaragua",
    "Niger",
    "Nigéria",
    "Norvège",
    "Nouvelle-Zélande",
    "Oman",
    "Pakistan",
    "Palaos",
    "Panama",
    "Pérou",
    "Philippines",
    "Pologne",
    "Portugal",
    "Qatar",
    "Roumanie",
    "Royaume-Uni",
    "Rwanda",
    "Saint-Kitts-et-Nevis",
    "Saint-Vincent-et-les-Grenadines",
    "Sao Tomé-et-Principe",
    "Serbie",
    "Seychelles",
    "Singapour",
    "Slovénie",
    "Somalie",
    "Soudan",
    "Sri Lanka",
    "Suède",
    "Swaziland",
    "Suisse",
    "Syrie",
    "Tadjikistan",
    "Tanzanie",
    "Thaïlande",
    "Timor oriental",
    "Togo",
    "Tonga",
    "Trinité-et-Tobago",
    "Tunisie",
    "Turkménistan",
    "Turquie",
    "Vanuatu",
    "Vatican",
    "Venezuela",
    "Viêt Nam",
    "Yémen",
    "Zambie",
    "Zimbabwe"
];

const input = document.getElementById('userInput')
const list = document.getElementById('country-list')
let selectedCountries = countries

function initCountries() {
    list.innerHTML = ''
    selectedCountries.forEach(country => {
        const listItem = document.createElement('li')
        listItem.innerHTML = country
        list.appendChild(listItem)
    })
}

initCountries()

input.addEventListener('keyup', function(event) {
    const search = event.target.value
    selectedCountries = countries.filter(country => country.toLocaleLowerCase().indexOf(search.toLocaleLowerCase()) !== -1)
    initCountries()
})